# Pandas
-  Pandas
    - 데이터를 효과적으로 처리하고 시각화 해주는 라이브러리
    - Numpy와 함께 사용되어 다양한 연계적인 기능을 제공
    - Index에 따라 데이터 나열, Series를 기본적인 자료형으로 사용
    - Excel과 거의 비슷 
- Pandas Lib 설치
    - !pip install pandas 
    - !pip install seaborn 
- [api](https://pandas.pydata.org/docs/reference/frame.html) [api](https://pandas.pydata.org/docs/reference/index.html)

In [4]:
import numpy as np
import pandas as pd
import seaborn as sns                      # 통계 전용 시각화 - matplotlib 같이 사용 가능 

import matplotlib.pyplot as plt            # 그래프 출력 옵션 (Detail)
import matplotlib as mpl                   # 외적인(큰틀) 옵션 - 한글, 사이즈 등  

mpl.rc('font', family='Malgun Gothic')     # 폰트 경로 - C:\Windows\Fonts\Malgun Gothic
plt.rcParams['axes.unicode_minus']=False   # 마이너스 설정

## 자료형
### Series 자료형
- 1차원 배열 (list, numpy)
- index, value 구성
- 하나의 데이터 타입만 가능

In [7]:
# 1월 ~ 4월 까지의 평균 온도 데이터 (-20, -10, 10, 20)
temp=[-20, 10, 10, 20]        # list 생성
temp_df=pd.Series(data=temp)    
temp_df

0   -20
1    10
2    10
3    20
dtype: int64

In [9]:
type(temp_df)

pandas.Series

In [11]:
# index 지정 
temp_idx=pd.Series(data=temp, index=["1월", "2월", "3월", "4월"])
temp_idx

1월   -20
2월    10
3월    10
4월    20
dtype: int64

In [23]:
# numpy 생성 
data=np.random.randint(0, 100, 5)      # 0 ~ 99 사이의 난수 5개
data_df=pd.Series(data, index=["월", "화", "수", "목", "금"])
data_df

월    94
화    60
수    41
목    37
금    93
dtype: int32

### DataFrame 자료형
- 2차원 배열 (list, dictionary, numpy)
- index, values, columns 구성
- 실무에서 가장 많이 사용하는 형태

In [48]:
# list 생성
emp_list=[['001', '채치수', '사원'],
         ['002', '정대만', '사원'],
         ['003', '송태섭', '주임'],
         ['004', '서태웅', '주임'],
         ['005', '강백호', '선임']]

emp_list
emp_list_df=pd.DataFrame(data=emp_list, columns=['사원번호', '사원명', '직급'])       
emp_list_df

  사원번호  사원명  직급
0  001  채치수  사원
1  002  정대만  사원
2  003  송태섭  주임
3  004  서태웅  주임
4  005  강백호  선임

In [54]:
# dict 생성
emp_dict={
    '사원번호' : ['001', '002', '003', '004', '005'],
    '사원명' : ['채치수', '정대만', '송태섭', '서태웅', '강백호'],
    '직급' : ['사원', '사원', '주임', '주임', '선임']
}
emp_dict=pd.DataFrame(data=emp_dict)
emp_dict

  사원번호  사원명  직급
0  001  채치수  사원
1  002  정대만  사원
2  003  송태섭  주임
3  004  서태웅  주임
4  005  강백호  선임

In [69]:
# ndarray 생성 
val_arr=np.arange(12).reshape(3, 4)
val_arr

val_arr_df=pd.DataFrame(data=val_arr, index=['one', 'two', 'three'], columns=['A', 'B', 'C', 'D'])
val_arr_df

       A  B   C   D
one    0  1   2   3
two    4  5   6   7
three  8  9  10  11

In [71]:
# DataFrame을 list, ndarray, dictionary 변환
my_list=emp_list_df.values.tolist()
print(my_list, type(my_list), '\n')

my_dict=emp_list_df.to_dict()
print(my_dict, type(my_dict), '\n')

my_numpy=emp_list_df.to_numpy()
print(my_numpy, type(my_numpy))

[['001', '채치수', '사원'], ['002', '정대만', '사원'], ['003', '송태섭', '주임'], ['004', '서태웅', '주임'], ['005', '강백호', '선임']] <class 'list'>

{'사원번호': {0: '001', 1: '002', 2: '003', 3: '004', 4: '005'}, '사원명': {0: '채치수', 1: '정대만', 2: '송태섭', 3: '서태웅', 4: '강백호'}, '직급': {0: '사원', 1: '사원', 2: '주임', 3: '주임', 4: '선임'}} <class 'dict'>

[['001' '채치수' '사원']
 ['002' '정대만' '사원']
 ['003' '송태섭' '주임']
 ['004' '서태웅' '주임']
 ['005' '강백호' '선임']] <class 'numpy.ndarray'>

### 파일 저장 
- 파일 저장 csv, xlsx

In [83]:
# csv
emp_df.to_csv('./Data_Result/emp.csv', encoding='cp949', index=False)          # 또는 encoding='utf-8-sig'

In [85]:
# excel 
emp_df.to_excel('./Data_Result/emp.xlsx', index=False)

- 파일 불러오기 csv, xlsx

In [88]:
# csv
pd.read_csv('./Data_Result/emp.csv', encoding='cp949')

   사원번호  사원명  직급
0     1  채치수  사원
1     2  정대만  사원
2     3  송태섭  주임
3     4  서태웅  주임
4     5  강백호  선임

In [90]:
# Excel
pd.read_excel('./Data_Result/emp.xlsx')

   사원번호  사원명  직급
0     1  채치수  사원
1     2  정대만  사원
2     3  송태섭  주임
3     4  서태웅  주임
4     5  강백호  선임

In [92]:
# 참고] text 저장 및 불러오기
# emp_df.to_csv('./Data_Result/emp.txt', sep='\t')
# pd.read_csv('./Data_Result/emp.txt', sep='\t')

## DDA 
- Descriptive Data Analysis (DDA, 기술적 데이터 분석) 
- 데이터 불러오기 
- 데이터 구조와 타입 파악 
- 기술 통계량 확인

### 데이터 불러오기

In [83]:
dye=pd.read_csv('./Data_Set/염색공정.csv', encoding='cp949')    # csv 파일 읽기

In [106]:
dye.shape          # 데이터 크기 확인 (행, 열)

(32608, 7)

In [108]:
dye.head()         # 데이터 획인 >> 기본 값(앞 부분 5개)

    설비번호  투입중량(kg)  염색길이(m)  지시온도  진행온도  공정진행시간(%)   염색색차 DE
0  FCM08      44.6     41.0  30.0  10.9       0.19  0.753096
1  FCM08      44.6     41.0  30.0  10.3       0.39  0.753096
2  FCM08      44.6     41.0  30.0  10.3       0.58  0.753096
3  FCM08      44.6     41.0  30.0  10.2       0.77  0.753096
4  FCM08      44.6     41.0  30.0  10.8       0.97  0.753096

- 설비번호 : 기계 번호
- 투입중량(kg) : 원단 무게 
- 염색길이(m) : 원단 길이
- 지시온도 : 목표 온도 (작업자가 설정한 기준)
- 진행온도 : 공정 상태 온도 (실제 작업 온도)
- 공정진행시간(%) : 공정 진행률 (몇 % 진행되었는지)
- 염색색차 DE : 품질 지표 또는 품질 점수 (결과)
- 참고]
    - 물량(원단) : 투입중량, 길이
    - 공정(기계) : 설비번호, 지시온도, 진행온도, 진행률
    - 결과(품질 측정) : 염색색차 DE

In [111]:
dye.head(2)

    설비번호  투입중량(kg)  염색길이(m)  지시온도  진행온도  공정진행시간(%)   염색색차 DE
0  FCM08      44.6     41.0  30.0  10.9       0.19  0.753096
1  FCM08      44.6     41.0  30.0  10.3       0.39  0.753096

In [117]:
dye.tail()         # 뒤 부분 데이터 확인
dye.tail(2)

        설비번호  투입중량(kg)  염색길이(m)  지시온도  진행온도  공정진행시간(%)   염색색차 DE
32606  FCM11     234.2    433.0  30.0  29.8      99.52  1.696731
32607  FCM11     234.2    433.0  30.0  29.8     100.00  1.696731

### 데이터 구조 파악
- 데이터 타입 : 연속형(숫자), 범주형(문자), 순서형(날짜)
- 데이터 사이즈 : 행, 열 개수
- 결측치 : 빈 값

In [966]:
dye.info()          # 데이터 요약 정보 >> 컬럼명, 사이즈(결측치), 데이터타입

<class 'pandas.DataFrame'>
RangeIndex: 32608 entries, 0 to 32607
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   설비번호       32608 non-null  str
 1   투입중량(kg)   32608 non-null  float64
 2   염색길이(m)    32608 non-null  float64
 3   지시온도       32608 non-null  float64
 4   진행온도       32608 non-null  float64
 5   공정진행시간(%)  32608 non-null  float64
 6   염색색차 DE    32608 non-null  float64
dtypes: float64(6), str(1)
memory usage: 1.9 MB

### 기술적 통계량
- 연속형(숫자) 통계량 : 평균, 중앙값, 최소값, 최대값, 분산, 표준편차
- 범주형(문자) 통계량 : 빈도수

In [969]:
# 연속형(숫자) 통계량
dye['염색색차 DE'].describe().round(2)

count    32608.00
mean         2.08
std          3.01
min          0.09
25%          0.60
50%          1.32
75%          2.02
max         17.20
Name: 염색색차 DE, dtype: float64

In [973]:
print("평균값:", dye['염색색차 DE'].mean())
print("중앙값:", dye['염색색차 DE'].median())
print("최소값:", dye['염색색차 DE'].min())
print("최대값:", dye['염색색차 DE'].max())
print("분산:", dye['염색색차 DE'].var())
print("표준편차:", dye['염색색차 DE'].std())

평균값: 2.0817785645406035
중앙값: 1.315164
최소값: 0.08812822
최대값: 17.20203
분산: 9.076572029080268
표준편차: 3.012734974915694

In [121]:
dye[['지시온도', '진행온도']].describe().T.round(2)

        count   mean    std  min   25%   50%    75%    max
지시온도  32608.0  85.02  31.39  0.0  70.0  83.4  112.8  135.0
진행온도  32608.0  84.80  31.29  0.0  67.2  83.4  112.4  137.4

In [977]:
dye[['지시온도', '진행온도']].mean()

지시온도    85.017045
진행온도    84.804809
dtype: float64

In [979]:
dye.describe().T.round(2)        # 정수형 전체

             count    mean     std    min    25%     50%     75%     max
투입중량(kg)   32608.0  137.23   87.66  19.80  60.80  113.80  189.20   368.0
염색길이(m)    32608.0  246.53  379.27   2.00  24.00   87.00  301.00  1600.0
지시온도       32608.0   85.02   31.39   0.00  70.00   83.40  112.80   135.0
진행온도       32608.0   84.80   31.29   0.00  67.20   83.40  112.40   137.4
공정진행시간(%)  32608.0   49.79   28.83   0.17  24.82   49.64   74.64   100.0
염색색차 DE    32608.0    2.08    3.01   0.09   0.60    1.32    2.02    17.2

In [85]:
# 범주형(문자) 통계량 - 빈도수 
dye['설비번호'].nunique()         # 데이터(빈도) 값 개수

7

In [87]:
dye['설비번호'].unique()          # 데이터(빈도) 값 내용

<ArrowStringArray>
['FCM08', 'FCM11', 'FCM06', 'FCM07', 'FCM05', 'FCM12', 'FCM15']
Length: 7, dtype: str

In [89]:
dye['설비번호'].value_counts()    # 데이터 값과 빈도수

설비번호
FCM08    8952
FCM05    6171
FCM06    5774
FCM11    4442
FCM12    3699
FCM15    1903
FCM07    1667
Name: count, dtype: int64

In [984]:
dye.describe(include='str')

         설비번호
count   32608
unique      7
top     FCM08
freq     8952

## 데이터 가공 
- 분석 목적에 맞게 데이터를 재구성하거나 형태를 바꾸는 과정
- 필터링, 컬럼 선택/재구성, 정렬 등

### 데이터 필터링
- 필터링은 데이터에서 필요한 행/열만 선택하는 과정
    - iloc[row, column] : 위치(숫자) 기반  인덱싱 
    - loc[row, column] : 라벨(이름) 기반 인덱싱 
    - boolean indexing : 조건을 이용한 데이터 선택

#### iloc
- iloc[row, column] 
- 위치(숫자) 기반 인덱싱

In [96]:
dye=pd.read_csv('./Data_Set/염색공정.csv', encoding='cp949')

In [98]:
# 원하는 행열 
dye.iloc[5:15, 2:4]     # 행 5 ~ 14, 열 2 ~ 3

# 모든 행 
dye.iloc[:, :4]         # 열 0 ~ 3  
dye.iloc[:, 4:]         # 열 4 ~ 
dye.iloc[:, [1, 2]]     # 열 1, 2
dye.iloc[:, :-1]        # 마지막 열 제외
dye.iloc[:, -1:]        # 마지막 열만 

# 모든 열 
dye.iloc[:3, :]         # 행 0 ~ 2  / 참고 dye.iloc[:3, ] 열 생략 가능, 행 불가

    설비번호  투입중량(kg)  염색길이(m)  지시온도  진행온도  공정진행시간(%)   염색색차 DE
0  FCM08      44.6     41.0  30.0  10.9       0.19  0.753096
1  FCM08      44.6     41.0  30.0  10.3       0.39  0.753096
2  FCM08      44.6     41.0  30.0  10.3       0.58  0.753096

#### loc
- loc[row, column] : 명칭 기반 인덱싱

In [101]:
dye.loc[4:20, '설비번호':'진행온도'].head()

    설비번호  투입중량(kg)  염색길이(m)  지시온도  진행온도
4  FCM08      44.6     41.0  30.0  10.8
5  FCM08      44.6     41.0  30.0  10.8
6  FCM08      44.6     41.0  30.0  10.9
7  FCM08      44.6     41.0  30.0  11.1
8  FCM08      44.6     41.0  30.5  14.0

In [103]:
dye.loc[:, ['설비번호', '진행온도', '염색색차 DE']].head()

    설비번호  진행온도   염색색차 DE
0  FCM08  10.9  0.753096
1  FCM08  10.3  0.753096
2  FCM08  10.3  0.753096
3  FCM08  10.2  0.753096
4  FCM08  10.8  0.753096

In [105]:
imsi=dye.copy()                                    # 주로 시계열에서 사용
imsi.set_index('설비번호', inplace=True)          
imsi.sort_values(by='설비번호', inplace=True)
imsi.head()

       투입중량(kg)  염색길이(m)  지시온도  진행온도  공정진행시간(%)  염색색차 DE
설비번호
FCM05     198.4    500.0  30.0  31.0       0.37  5.25213
FCM05     198.4    500.0  30.0  32.0       0.75  5.25213
FCM05     198.4    500.0  30.0  32.8       1.12  5.25213
FCM05     198.4    500.0  30.0  33.8       1.49  5.25213
FCM05     198.4    500.0  30.0  33.5       1.87  5.25213

In [107]:
imsi.index.value_counts()

설비번호
FCM08    8952
FCM05    6171
FCM06    5774
FCM11    4442
FCM12    3699
FCM15    1903
FCM07    1667
Name: count, dtype: int64

In [123]:
imsi.loc["FCM05":"FCM08", "지시온도":"염색색차 DE"].head()

       지시온도  진행온도  공정진행시간(%)  염색색차 DE
설비번호
FCM05  30.0  31.0       0.37  5.25213
FCM05  30.0  32.0       0.75  5.25213
FCM05  30.0  32.8       1.12  5.25213
FCM05  30.0  33.8       1.49  5.25213
FCM05  30.0  33.5       1.87  5.25213

In [114]:
fcm=imsi.loc["FCM05", :]
fcm['염색색차 DE'].mean().round(2)       # fcm.describe().T.round(2)

2.81

In [125]:
# 구간 여러 개 붙이기
pd.concat([
    dye.loc[:, '설비번호':'염색길이(m)'], 
    dye.loc[:, '공정진행시간(%)':'염색색차 DE']
], axis=1).head()

    설비번호  투입중량(kg)  염색길이(m)  공정진행시간(%)   염색색차 DE
0  FCM08      44.6     41.0       0.19  0.753096
1  FCM08      44.6     41.0       0.39  0.753096
2  FCM08      44.6     41.0       0.58  0.753096
3  FCM08      44.6     41.0       0.77  0.753096
4  FCM08      44.6     41.0       0.97  0.753096

#### 조건기반 인덱싱 
- 조건기반 인덱싱 (boolean indexing)
    - 문법 : 데이터프레임의 조건식을 직접 사용하여 필터링
        - 예 : df[df['column'] > value]
    - 장점 : Python 코드의 기본 문법을 사용하므로 직관적이고 유연함
    - 단점 : 조건이 복잡해지면 가독성이 떨어질 수 있음

In [115]:
# 불량 >> 품질 기준을 벗어난 데이터만 확인 
fail=dye[dye['염색색차 DE'] > 3]
fail.shape

(4953, 7)

In [117]:
len(fail) / len(dye) * 100         # 불량률 계산

15.189524043179588

- 불량
    - 설비별 불량률 비교
    - 공정 조건 영향

In [120]:
fail['설비번호'].value_counts()        # 설비별 불량 건수 (0 안나옴) / FCM06, FCM15

설비번호
FCM05    1907
FCM12     984
FCM08     920
FCM07     817
FCM11     325
Name: count, dtype: int64

In [122]:
bad=dye[dye['설비번호'] == 'FCM07']     # 불량률이 가장 높음 (계산은 그룹함수)
bad.describe().T.round(2)

            count    mean    std     min     25%     50%     75%     max
투입중량(kg)   1667.0  295.16  29.82  260.40  264.50  288.20  341.60  341.80
염색길이(m)    1667.0  459.63  56.87  373.00  413.00  450.00  545.00  545.00
지시온도       1667.0   73.56  32.05   20.00   40.75   70.00  102.40  120.00
진행온도       1667.0   73.70  31.84   17.80   42.85   71.70  102.05  121.60
공정진행시간(%)  1667.0   50.24  28.88    0.39   25.30   50.24   75.21  100.00
염색색차 DE    1667.0    2.71   1.09    0.77    1.91    2.16    3.71    3.93

In [126]:
good=dye[dye['설비번호'] == 'FCM06']
good.describe().T.round(2)

            count    mean     std    min     25%     50%     75%    max
투입중량(kg)   5774.0  148.28   38.20  93.40  112.40  155.80  164.20  219.4
염색길이(m)    5774.0  190.87  180.55   5.00   24.00   90.00  343.00  601.0
지시온도       5774.0   84.52   28.12   4.00   70.00   82.00  108.60  130.0
진행온도       5774.0   84.28   27.94  19.00   68.70   82.20  108.38  137.1
공정진행시간(%)  5774.0   49.39   28.71   0.19   24.62   49.04   73.96  100.0
염색색차 DE    5774.0    1.18    0.66   0.30    0.55    1.11    1.59    2.6

In [476]:
# Ex1) FCM07 설비이면서 동시에 정상인 데이터만 뽑기
num=dye['설비번호'] == 'FCM07'
de=dye['염색색차 DE'] < 2
result=dye[num & de]      # [cond1 | ~cond2]
result.head()

       설비번호  투입중량(kg)  염색길이(m)  지시온도  진행온도  공정진행시간(%)   염색색차 DE
3114  FCM07     341.6    545.0  30.0  42.4       0.47  1.958902
3115  FCM07     341.6    545.0  30.0  30.1       0.93  1.958902
3116  FCM07     341.6    545.0  30.0  29.3       1.40  1.958902
3117  FCM07     341.6    545.0  30.0  29.8       1.87  1.958902
3118  FCM07     341.6    545.0  30.0  30.4       2.34  1.958902

In [480]:
#  Ex2) 평균 온도보다 높게 작업된 데이터 뽑기
avg_temp=dye['진행온도'].mean()
cond=dye['진행온도'] > avg_temp
result=dye[cond]
result.shape

result.loc[:, ['설비번호', '진행온도', '지시온도']].head()

     설비번호  지시온도
40  FCM08  84.0
41  FCM08  84.9
42  FCM08  85.9
43  FCM08  86.9
44  FCM08  88.0

### 구조 변경
- Column 생성, 수정, 삭제
#### 추가

In [1089]:
dye=pd.read_csv("./Data_Set/염색공정.csv", encoding='cp949')

In [1093]:
dye.head()

    설비번호  투입중량(kg)  염색길이(m)  지시온도  진행온도  공정진행시간(%)   염색색차 DE
0  FCM08      44.6     41.0  30.0  10.9       0.19  0.753096
1  FCM08      44.6     41.0  30.0  10.3       0.39  0.753096
2  FCM08      44.6     41.0  30.0  10.3       0.58  0.753096
3  FCM08      44.6     41.0  30.0  10.2       0.77  0.753096
4  FCM08      44.6     41.0  30.0  10.8       0.97  0.753096

In [1082]:
copy_dye=dye.copy()

In [1084]:
# 생성(추가) / 파생변수 - column 추가
copy_dye['상태']=np.where(dye['염색색차 DE'] > 3, '불량', '정상')

In [1086]:
copy_dye.head()

    설비번호  투입중량(kg)  염색길이(m)  지시온도  진행온도  공정진행시간(%)   염색색차 DE  상태
0  FCM08      44.6     41.0  30.0  10.9       0.19  0.753096  정상
1  FCM08      44.6     41.0  30.0  10.3       0.39  0.753096  정상
2  FCM08      44.6     41.0  30.0  10.3       0.58  0.753096  정상
3  FCM08      44.6     41.0  30.0  10.2       0.77  0.753096  정상
4  FCM08      44.6     41.0  30.0  10.8       0.97  0.753096  정상

In [1073]:
copy_dye['상태'].value_counts()

상태
정상    27655
불량     4953
Name: count, dtype: int64

In [1096]:
# EX1) 생성(추가) / 파생변수 - column 추가 후 원하는 위치
minus=copy_dye['지시온도'] - copy_dye['진행온도']

copy_dye.insert(loc=copy_dye.columns.get_loc('진행온도') + 1,     # 추가 위치
                column='온도편차',    # 추가할 컬럼명
                value=minus)          # 추가할 값
copy_dye.head(2)

    설비번호  투입중량(kg)  염색길이(m)  지시온도  진행온도  온도편차  공정진행시간(%)   염색색차 DE  상태
0  FCM08      44.6     41.0  30.0  10.9  19.1       0.19  0.753096  정상
1  FCM08      44.6     41.0  30.0  10.3  19.7       0.39  0.753096  정상

#### 수정

In [1104]:
copy_dye.rename(columns={'투입중량(kg)':'투입중량_kg',
                         '염색길이(m)':'염색길이_m',
                         '공정진행시간(%)':'공정진행시간_%',
                         '염색색차 DE':'염색색차_DE'},
                inplace=True)
copy_dye.head()

    설비번호  투입중량_kg  염색길이_m  지시온도  진행온도  온도편차  공정진행시간_%   염색색차_DE  상태
0  FCM08     44.6    41.0  30.0  10.9  19.1      0.19  0.753096  정상
1  FCM08     44.6    41.0  30.0  10.3  19.7      0.39  0.753096  정상
2  FCM08     44.6    41.0  30.0  10.3  19.7      0.58  0.753096  정상
3  FCM08     44.6    41.0  30.0  10.2  19.8      0.77  0.753096  정상
4  FCM08     44.6    41.0  30.0  10.8  19.2      0.97  0.753096  정상

#### 삭제

In [1106]:
copy_dye.drop(columns=['온도편차', '상태'], inplace=True)
copy_dye.head(2)

    설비번호  투입중량_kg  염색길이_m  지시온도  진행온도  공정진행시간_%   염색색차_DE
0  FCM08     44.6    41.0  30.0  10.9      0.19  0.753096
1  FCM08     44.6    41.0  30.0  10.3      0.39  0.753096

In [1108]:
copy_dye.drop(index=copy_dye.index[0:10], inplace=True)
copy_dye.shape      # (32608, 5)   실행다시

(32598, 7)

In [203]:
copy_dye.reset_index(inplace=True)

### 값 변경
- replace() : 다른 값으로 단순 치환
- apply() : 함수를 이용한 데이터 변형/연산

In [1110]:
copy_dye.head()

     설비번호  투입중량_kg  염색길이_m  지시온도  진행온도  공정진행시간_%   염색색차_DE
10  FCM08     44.6    41.0  37.0  37.0      2.13  0.753096
11  FCM08     44.6    41.0  40.0  40.3      2.32  0.753096
12  FCM08     44.6    41.0  40.0  39.4      2.51  0.753096
13  FCM08     44.6    41.0  40.0  39.2      2.71  0.753096
14  FCM08     44.6    41.0  42.5  44.7      2.90  0.753096

In [1112]:
copy_dye['설비번호']=copy_dye['설비번호'].replace('FCM08', 'FCM_NEW')    # 두개 이상 { }

In [1114]:
copy_dye.head()

       설비번호  투입중량_kg  염색길이_m  지시온도  진행온도  공정진행시간_%   염색색차_DE
10  FCM_NEW     44.6    41.0  37.0  37.0      2.13  0.753096
11  FCM_NEW     44.6    41.0  40.0  40.3      2.32  0.753096
12  FCM_NEW     44.6    41.0  40.0  39.4      2.51  0.753096
13  FCM_NEW     44.6    41.0  40.0  39.2      2.71  0.753096
14  FCM_NEW     44.6    41.0  42.5  44.7      2.90  0.753096

In [ ]:
# copy_dye['품질']=np.where(copy_dye['염색색차_DE'] > 3, "불량", np.where(copy_dye['염색색차_DE'] > 2, "이상", "정상"))

In [1116]:
def sub(val):
    if val > 3:           
        return "불량"
    elif val > 2:         
        return "이상"
    elif val <= 2:         
        return "정상"

copy_dye['품질']=copy_dye['염색색차_DE'].apply(sub)

In [1118]:
copy_dye['품질'].value_counts()

품질
정상    23633
불량     4953
이상     4012
Name: count, dtype: int64

### 실습

In [51]:
dye=pd.read_csv('./Data_Set/염색공정.csv', encoding='cp949')

In [53]:
# 컬럼명 변경 
dye.rename(columns={'투입중량(kg)':'투입중량_kg',
                    '염색길이(m)':'염색길이_m',
                    '공정진행시간(%)':'공정진행시간_%',
                    '염색색차 DE':'염색색차_DE'},
                inplace=True)
dye.head()

    설비번호  투입중량_kg  염색길이_m  지시온도  진행온도  공정진행시간_%   염색색차_DE
0  FCM08     44.6    41.0  30.0  10.9      0.19  0.753096
1  FCM08     44.6    41.0  30.0  10.3      0.39  0.753096
2  FCM08     44.6    41.0  30.0  10.3      0.58  0.753096
3  FCM08     44.6    41.0  30.0  10.2      0.77  0.753096
4  FCM08     44.6    41.0  30.0  10.8      0.97  0.753096

In [55]:
# 파생변수
dye['불량여부']=(dye['염색색차_DE'] > 3).astype(int)    # 정상 0, 불량 1

In [57]:
dye.head()

    설비번호  투입중량_kg  염색길이_m  지시온도  진행온도  공정진행시간_%   염색색차_DE  불량여부
0  FCM08     44.6    41.0  30.0  10.9      0.19  0.753096     0
1  FCM08     44.6    41.0  30.0  10.3      0.39  0.753096     0
2  FCM08     44.6    41.0  30.0  10.3      0.58  0.753096     0
3  FCM08     44.6    41.0  30.0  10.2      0.77  0.753096     0
4  FCM08     44.6    41.0  30.0  10.8      0.97  0.753096     0

In [59]:
# 파생변수
calc=dye['투입중량_kg'] / dye['염색길이_m']

dye.insert(loc=dye.columns.get_loc('염색길이_m') + 1, 
           column='투입중량/길이', 
           value=calc)

In [62]:
dye.head()

    설비번호  투입중량_kg  염색길이_m   투입중량/길이  지시온도  진행온도  공정진행시간_%   염색색차_DE  불량여부
0  FCM08     44.6    41.0  1.087805  30.0  10.9      0.19  0.753096     0
1  FCM08     44.6    41.0  1.087805  30.0  10.3      0.39  0.753096     0
2  FCM08     44.6    41.0  1.087805  30.0  10.3      0.58  0.753096     0
3  FCM08     44.6    41.0  1.087805  30.0  10.2      0.77  0.753096     0
4  FCM08     44.6    41.0  1.087805  30.0  10.8      0.97  0.753096     0

In [65]:
dye.to_csv('./Data/염색공정_수정.csv', encoding='cp949', index=False)

## 정렬
- 단일, 다수 컬럼 정렬
- 내림차순, 오름차순 정럴
### 단일 컬럼 정렬

In [137]:
dye=pd.read_csv('./Data_Set/염색공정_수정.csv', encoding='cp949')

In [141]:
# 염색 색차 정렬 - 오름 차순
dye.sort_values(by='염색색차_DE').head()      # 원본 데이터 영향을 안 준다. by 생략 가능

       설비번호  투입중량_kg  염색길이_m   투입중량/길이  지시온도  진행온도  공정진행시간_%   염색색차_DE  불량여부
6269  FCM08     76.2    11.0  6.927273  87.6  87.3     66.45  0.088128     0
6210  FCM08     76.2    11.0  6.927273  86.1  86.8     27.63  0.088128     0
6209  FCM08     76.2    11.0  6.927273  84.5  85.4     26.97  0.088128     0
6208  FCM08     76.2    11.0  6.927273  83.0  85.5     26.32  0.088128     0
6207  FCM08     76.2    11.0  6.927273  81.5  81.7     25.66  0.088128     0

In [143]:
# 염색 색차 정렬 - 내림 차순
dye.sort_values(by='염색색차_DE', ascending=False).head()

,설비번호,투입중량_kg,염색길이_m,투입중량/길이,지시온도,진행온도,공정진행시간_%,염색색차_DE,불량여부
10297,FCM05,111.0,115.0,0.965217,103.1,102.8,20.25,17.20203,1
10354,FCM05,111.0,115.0,0.965217,120.6,119.6,37.73,17.20203,1
10356,FCM05,111.0,115.0,0.965217,116.6,115.7,38.34,17.20203,1
10357,FCM05,111.0,115.0,0.965217,114.7,114.2,38.65,17.20203,1
10358,FCM05,111.0,115.0,0.965217,112.7,112.3,38.96,17.20203,1

### 다수(n) 컬럼 정렬

In [146]:
dye.sort_values(by=['설비번호', '염색색차_DE']).head()                    # 오름차순, 오름차순

        설비번호  투입중량_kg  염색길이_m   투입중량/길이  지시온도  진행온도  공정진행시간_%   염색색차_DE  불량여부
20948  FCM05    128.0   273.0  0.468864  30.0  28.8      0.50  0.200785     0
20949  FCM05    128.0   273.0  0.468864  30.0  28.6      0.99  0.200785     0
20950  FCM05    128.0   273.0  0.468864  30.0  28.5      1.49  0.200785     0
20951  FCM05    128.0   273.0  0.468864  30.0  28.5      1.98  0.200785     0
20952  FCM05    128.0   273.0  0.468864  30.0  28.5      2.48  0.200785     0

In [148]:
dye.sort_values(by=['설비번호', '염색색차_DE'], ascending=False).head()       # 오름차순, 내림차순

        설비번호  투입중량_kg  염색길이_m  투입중량/길이  지시온도  진행온도  공정진행시간_%   염색색차_DE  불량여부
16676  FCM15    188.4  1600.0  0.11775  30.0  33.9      0.38  0.506896     0
16677  FCM15    188.4  1600.0  0.11775  30.0  37.9      0.75  0.506896     0
16678  FCM15    188.4  1600.0  0.11775  30.0  39.7      1.13  0.506896     0
16679  FCM15    188.4  1600.0  0.11775  30.0  39.5      1.51  0.506896     0
16680  FCM15    188.4  1600.0  0.11775  30.0  40.1      1.89  0.506896     0

In [150]:
# 내림차순정렬, 원본데이터 직접변경, 인덱스 재정의 
dye.sort_values(by=['설비번호', '염색색차_DE'], 
                ascending=[False, False], 
                inplace=True, 
                ignore_index=True)

In [152]:
dye.head()

    설비번호  투입중량_kg  염색길이_m  투입중량/길이  지시온도  진행온도  공정진행시간_%   염색색차_DE  불량여부
0  FCM15    188.4  1600.0  0.11775  30.0  33.9      0.38  0.506896     0
1  FCM15    188.4  1600.0  0.11775  30.0  37.9      0.75  0.506896     0
2  FCM15    188.4  1600.0  0.11775  30.0  39.7      1.13  0.506896     0
3  FCM15    188.4  1600.0  0.11775  30.0  39.5      1.51  0.506896     0
4  FCM15    188.4  1600.0  0.11775  30.0  40.1      1.89  0.506896     0

In [154]:
# End Of ---------------------------------------------------------------------------